name: Deploy Project to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /var/www/projectmanagementtool

            git pull origin main

            echo "===== Backend ====="
            cd backend
            npm install
            pm2 restart backend
            pm2 save

            echo "===== Frontend ====="
            cd ../frontend
            npm install
            npm run build

            sudo systemctl reload nginx

            echo "Deployment completed successfully!"